### ISSUE TITLE
Scaffold backend data model for Task Skills

### ISSUE THREAD

**Issue by ChrisHoopes** [SlateFoundation/slate-cbl#148]
Each tasks that's created can have multiple skills assigned to it. We'll need to implement saving that relationship into the database based on the existing Task and Skill models. There is no ordering required, just associating multiple skills per task.

Create backend ActiveRecord implementations under the Slate\CBL\Tasks\ namespace:
- \Slate\CBL\Tasks\TaskSkill
  - extends \VersionedRecord

These will need to be returned along with the rest of the Tasks data in the Task RecordsRequestHandler.
### TaskID
- type: integer
### SkillID
- type: integer
### StudentTaskID
- type: integer
- default: null

The StudentTaskID is only used when additional skills are assigned to a task on a per-student level.
## UI Mockups

Example of multiple skills being assigned to a task in the interface:
![screen shot 2016-06-09 at 3 49 33 pm](https://cloud.githubusercontent.com/assets/966589/15944253/bcce77be-2e5a-11e6-8039-3b47ac5ccb18.png)

**Comment by themightychris** [comment]
It might make sense to split this into StudentTaskSkill and TaskSkill so that each can have a unique key on `[Student]TaskID+SkillID`

Then the dynamic field for embedding the list of skills can do a UNION query across the two tables and just return the distinct `SkillID`s

Maybe that will be messier in the long run with all the queries we need to do... I'm not sure but I'm inclined to lean toward starting with what lets us implement database constraints and indexes better
