### ISSUE TITLE
Implement the create task popup

### ISSUE THREAD

**Issue by ChrisHoopes** [SlateFoundation/slate-cbl#158]
Once the Create Task button is created make that launch the Create Task popup. This is already scaffolded out in the SlateModals app. **This functionality should exist in a shared package as it's used in both the Teacher dashboard and Tasks Manager.**

Fields in the popup include:
- title
- parent task
- type of experience
- due date
- expiration date
- students assigned to
- skills
- attachments
- instructions
- created by
- created date

Screenshot:
![screen shot 2016-06-16 at 11 26 59 am](https://cloud.githubusercontent.com/assets/966589/16131167/d19781f6-33da-11e6-8b9d-67cea90f2eb8.png)

**Regarding the Add Task to Database checkbox:** all tasks created in the Tasks Manager are automatically added to the database so this checkbox should be pre-selected and disabled. Tasks created elsewhere (teacher dashboard) can be added to the database to be re-used later. Only tasks added to the database show up in the Tasks Manager.

I believe this will require an additional boolean field indicated that a task is created in the Tasks Manager vs Teacher dashboard.

**Comment by nbey** [comment]
@ChrisHoopes  Should the `Title` field be a dropdown field? If so, are we querying the database for existing titles to show?

**Comment by ChrisHoopes** [comment]
@nbey yes it looks like they want to be able to easily recall past titles or type in a new one

**Comment by themightychris** [comment]
we'll need @ckunkel to confirm but I don't think the goal here is to help teachers reuse past titles -- that's something we want to prevent. I believe that this should search past titles, and if the teacher selects one of the results it should prompt them "Do you want to edit this existing task instead of creating a new one?"

Or maybe we just want to not have the title matching here since they already clicked "create new task" and that's just design relic from the teacher dashboard that's geared towards find-or-create?

**Comment by ckunkel** [comment]
Selecting a task already in the database is the goal here, which would pre load the core information in the form such as type of experience, skills and attachments. If they select an existing task rather than creating a new one, they should be able to change it in this window without changing the task in the database unless they choose ot save it by selecting the Add to Task Database button. 

To clarify the difference between similarly named tasks, the drop down search should list the name of the task and the creator, so they know if its theirs or someone else's.

**Comment by ChrisHoopes** [comment]
@nbey for right now in the TasksDatabase let's focus on just getting the tasks creation and editing process down. Also as per our recent discussion we can remove the following fields from the TasksDatabase popup since they're assignment specific:
- due date
- students assigned to

**Comment by ChrisHoopes** [comment]
@nbey see 173 about closing the window on creation and adding a toast
