### ISSUE TITLE
Implement task deleting

### ISSUE THREAD

**Issue by ChrisHoopes** [SlateFoundation/slate-cbl#160]
Once a task has been selected and highlighted the user should be able to click the Delete button. This will them prompt a deletion confirmation.

If the user confirms deletion, the task record should be marked as deleted and no longer shown in the Tasks Manager grid.

I don't believe we want to destroy any data but there's no plans for allowing users to un-delete tasks.

**Comment by themightychris** [comment]
@nbey We definitely want to do a soft delete here by adding a column `Status enum('shared','private','deleted')`

Maybe even override the ActiveRecord's delete/destroy methods to set Status=deleted instead of running DELETE queries, then that makes it impossible to do a hard delete via the ORM and lets us use all the default DELETE plumbing in emergence-apikit and RecordsRequestHandler. Just set the default browseConditions for the /tasks route to include `Status != "deleted"`

**Comment by ChrisHoopes** [comment]
@nbey please let me know when I can test this

**Comment by nbey** [comment]
@ChrisHoopes This should be ready for testing already.

**Comment by ChrisHoopes** [comment]
Looks good!
