### ISSUE TITLE
Teacher should be able to view read-only view of student dash

### ISSUE THREAD

**Issue by ChrisHoopes** [SlateFoundation/slate-cbl#297]
Teachers will be able to click on a student's name in the teacher dashboard to be taken to a read-only view of the student app on a per-source and per-student basis. The URL scheme should mimic what's done here: http://staging.b21-al.slatepowered.net/cbl/dashboards/demonstrations/student?content-area=ELA&student=areyes

The above passes the course section (which should already be linkable in the student app) and the student's user name to load their data. We should lock down the ability to change sections in this view and everything else should be read-only.

**Comment by themightychris** [comment]
@nbey @BillClinton I recommend addressing this along with the feedback provided in this PR in the same pass: https://github.com/SlateFoundation/slate-cbl/pull/280

The way the APIs are implemented right now is very similar to how the demonstrations APIs initially were (heavy reliance on dynamicFields and RecordsRequestHandlers extensions). Things got a _lot_ simpler and more performant when we moved away from that in favor of:
- Keep RecordsRequestHandlers simple -- instead of implementing subroutes for related things, stick to simple filters on root object routes (e.g. `/cbl/student-tasks?task=1234` instead of `/cbl/tasks/1234/student-tasks`). Notice that the RecordsRequestHandlers in [Slate\CBL\Demonstrations](https://github.com/SlateFoundation/slate-cbl/tree/releases/v2/develop/php-classes/Slate/CBL/Demonstrations) only override handleBrowseRequest
- Don't create dynamicFields for providing complex related data structures to the UI, instead create a plain (non-Records) request handler for each dashboard where its main view is loading the UI and it has api-only subroutes with optimized joins and simple params to get the novel big data structures each UI needs
  - See [StudentDashboardRequestHandler](https://github.com/SlateFoundation/slate-cbl/blob/releases/v2/develop/php-classes/Slate/CBL/Demonstrations/StudentDashboardRequestHandler.php) and [TeacherDashboardRequestHandler](https://github.com/SlateFoundation/slate-cbl/blob/releases/v2/develop/php-classes/Slate/CBL/Demonstrations/TeacherDashboardRequestHandler.php)
    - Replicate the patterns in these as much as possible, esp how StudentDashboardRequestHandler has a unified ways to grab the requested student
    - The one aspect of these that we **don't** want to replicate is the `handleDashboardRequest` method passing data (ContentArea and students/Student) into the template to help bootstrap the application. Issue #129 is about removing them and making the client-side code handle parsing any query params and loading such data async via API. This is necessary to support local debugging from a static HTML file against arbitrary remote apiHosts, and is also a best practice because it speeds up the initial load of the page.

**Comment by ChrisHoopes** [comment]
@BillClinton moved to Jira
