### ISSUE TITLE
DemonstrationsTeacher - Skill coloring not in agreement with competency color

### ISSUE THREAD

**Issue by ckunkel** [SlateFoundation/slate-cbl#412]
In the DemonstrationsTeacher app on the QA site, the competency shows level 10 (Y2) while the skills show level 9 (Y1) ratings. The ratings for level 9 are viewable in the student view, which is how you can confirm that the data is showing for the previously completed level. 

![screen shot 2018-01-22 at 4 00 54 pm](https://user-images.githubusercontent.com/5123794/35244253-8ba938bc-ff8d-11e7-9410-b78992c7e9b3.png)

**Comment by themightychris** [comment]
@ckunkel this is fixed in 70de12fdf4a6a7d404cc3d9498ab628ceeb9ca0b, build is updated on cbl-qa

With the new api/load model, we're loading _all_ StudentCompetency records from the server for the selected students and competencies, and sorting out client-side which to show. This logic was missing initially, resulting in haphazard selection of which StudentCompetency record to use for each student.

One untapped benefit to keep in mind is that we now have the data available and the ability to switch rendering for the student competencies "beneath" the ones initially seen. So we could in the future, without major changes to the data layer or rendering pipeline, provide controls within this interface to let teachers "flip back" through a student's previous levels in a competency. Picture a little back arrow or down arrow on the right side of each main cell that is only visible when you rollover. When you click it in a yellow cell that cell and any expanded demos below it would switch to pink level 1 data and a forward/up arrow would become visible for flipping back (and maybe the return arrow stays visible even when you're not rolling over to keep it evident you're seeing past data)
