### ISSUE TITLE
Manually clean up data where StudentTask rows have different ExperienceType than Task row

### ISSUE THREAD

**Issue by themightychris** [SlateFoundation/slate-cbl#445]
Use this query to discover on each instance where StudentTask records have a different ExperienceType than their associated Task record does

```sql
SELECT st.ID AS StudentTaskID,
       st.ExperienceType AS StudentTaskExperienceType,
       t.ID AS TaskID,
       t.ExperienceType AS TaskExperienceType
  FROM cbl_student_tasks st
  JOIN cbl_tasks t
    ON t.ID = st.TaskID
 WHERE st.ExperienceType != t.ExperienceType;
```

The StudentTask version of the column is going to be removed in the upcoming release and a migration will delete the column. The migration will refuse to run though until all conflicts in the data are resolved. Ahead of the deployment, conflicting values should be reconciled manually

**Comment by ckunkel** [comment]
@themightychris because there is no way to edit the student_task expereincetype field, we can safely assume that any disagreement in the task and student_task records should defer to the task ExperienceType. 

We ran this script on West Ada previously to address this and I think it is safe to run it everywhere. Thoughts?

update cbl_student_tasks SET ExperienceType = (SELECT ExperienceType FROM cbl_tasks where cbl_tasks.ID = cbl_student_tasks.TaskID);

**Comment by themightychris** [comment]
That's what I thought, but I looked through a few instances and saw what
looked like novel values in some places at the StudentTask level so I
wanted you to take a look first. If you don't see anything concerning you
could run that query to blow out the StudentTask-level values

**Comment by ckunkel** [comment]
Updated.
