### ISSUE TITLE
implement standard overrides

### ISSUE THREAD

**Issue by themightychris** [SlateFoundation/slate-cbl#51]

**Comment by themightychris** [comment]
@ckunkel @jcunn302 I'm thinking of implementing that overrides will be a special type of demonstration or maybe just a binary flag on any demonstration. I think it will keep a lot of things cleaner internally and externally. I like the idea of "override" just being a flag on a demonstration, so in addition to having the override button that just collects comments and creates a mostly empty demonstration with the override flag on, it could also be a special value in the dropdown for level on one or more standards when logging a demo like "M" is... or maybe some other UI mechanism so you could still log a demonstrated level with the override

We've still never gotten clarification on how overrides should impact averages. Our last discussion of it I believe is in the comments of the "CBL Tool Logic" google doc and that currently ends with waiting for feedback from school partners.

**Comment by ckunkel** [comment]
@themightychris the display in the grid should be an O instead of a number or an M. Any remaining demonstrations that have not yet been logged for a given standard would be completed with an O. 

Overrides will not impact averages so should not be counted either as a score or as part of the average calculation. 

For the workflow, the override will be selected from the Standard Overview window, so it is only intended to override a single standard.  I do see the potential value in multiple overrides being done simultaneously, but I don't think that fits within the existing log window workflow because of the need to  log Type of Experience, Context, etc. I think it should be its own window that simply says "confirm override to autocomplete level XX of skill xxxxxx?" and then require a comment to be left to explain.

**Comment by jcunn302** [comment]
@ckunkel Once an override has been completed, do we show the override comment in the standards overview window?

**Comment by ckunkel** [comment]
@jcunn302 yes, it can show similarly to other demonstrations with the comments included.

**Comment by themightychris** [comment]
@jcunn302 @ckunkel teacher dashboard is ready for testing overrides at dev-cbl

All that's left before I close this issue is updating the student dashboard to render overrides

**Comment by themightychris** [comment]
@jcunn302 @ckunkel student dashboard is ready for initial testing on dev-cbl now too

**Comment by themightychris** [comment]
@jcunn302 @ckunkel the issue with average-low flags on standards containing only overrides is fixed
